trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnectionACR: 'Container Images Diplomado M3'
  dockerRegistryServiceConnectionDockerHub: 'DockerHubConnection'
  imageRepositoryACR: 'nuevo-microservicio'
  imageRepositoryDockerHub: 'wilsonmontanoclaros/microservicio-python'
  containerRegistryACR: 'backendconteiner.azurecr.io'
  containerRegistryDockerHub: 'docker.io'
  tag: '1.0'
  vmImageName: 'ubuntu-latest'
  dockerfilePath: '$(Build.SourcesDirectory)/dockerfile'

stages:
- stage: Construccion
  displayName: "Construcción y Seguridad"
  jobs:
  - job: ConstruirYPublicar
    displayName: "Construir y Publicar Imagen en ACR y Docker Hub"
    pool:
      vmImage: $(vmImageName)
    steps:
      - script: |
          echo "Instalando Grype..."
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
          grype --version
        displayName: "Instalar Grype"

      - task: Docker@2
        displayName: "Construir Imagen Docker Local"
        inputs:
          command: build
          repository: $(imageRepositoryACR)
          dockerfile: $(dockerfilePath)
          containerRegistry: $(dockerRegistryServiceConnectionACR)
          tags: |
            $(tag)

      - script: |
          echo "Escaneando imagen Docker local..."
          docker images
          IMAGE_ID=$(docker images --format "{{.ID}}" | head -n 1)
          echo "Usando Image ID: $IMAGE_ID"
          grype "docker:$IMAGE_ID"
        displayName: "Grype Scan - Imagen Docker"

      # Push a Azure Container Registry
      - task: Docker@2
        displayName: "Push Imagen a ACR"
        condition: succeeded()
        inputs:
          command: push
          repository: $(imageRepositoryACR)
          containerRegistry: $(dockerRegistryServiceConnectionACR)
          tags: |
            $(tag)

      # Push a Docker Hub
      - task: Docker@2
        displayName: "Push Imagen a Docker Hub"
        condition: succeeded()
        inputs:
          command: push
          repository: $(imageRepositoryDockerHub)
          containerRegistry: $(dockerRegistryServiceConnectionDockerHub)
          tags: |
            $(tag)