apiVersion: apps/v1
kind: Deployment
metadata:
  name: mss-inventario
spec:
  selector:
    matchLabels:
      app: inventario
  replicas: 3
  template:
    metadata:
      labels:
        app: inventario
    spec:
      containers:
        - name: inventario
          image: wilsonmontanoclaros/microservicio-python:1.0